---
- name: Pull image from repository
  docker_image:
    name: eldadmwangi/eldad-yolo-backend:v1.0.0
    source: pull

- name: Create Node.js Backend Container
  docker_container:
    name: eldad-yolo-backend
    image: eldadmwangi/eldad-yolo-backend:v1.0.0
    networks:
      - name: app-net
    ports:
      - "4000:4000"
    command: "npm start"
    restart_policy: unless-stopped
  become: yes